### PR TITLE
Command line building

### PR DESCRIPTION
**Pull request by gravityrebel**

### CODE REVIEW

**Comment by jcaple-devtech** [comment]
What is the syntax to execute this from the CLI?

**Comment by seandotmoon** [comment]
It's supposed to be running as a stand along java app.
Try java -jar whatever jar file you get under target.

Also, slack will be easier method to get everyone's attention.

If any of you don't have slack mobile app, you don't want to miss that!!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by gravityrebel** [comment]
mvn assembly:assembly will run just the plugin. There may be a better way to integrate it into the mvn compile target, but I haven't looked into it yet. I was just trying to unblock anyone who was working on pipelines so that they could run the application from the command line.

**Comment by jcaple-devtech** [comment]
I am unable to run 'mvn assembly:assembly' using the code in this branch:

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building fuzzysystem 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-assembly-plugin:2.2-beta-5:assembly (default-cli) > package @ fuzzysystem >>>
[INFO]
[INFO] <<< maven-assembly-plugin:2.2-beta-5:assembly (default-cli) < package @ fuzzysystem <<<
[INFO]
[INFO]
[INFO] --- maven-assembly-plugin:2.2-beta-5:assembly (default-cli) @ fuzzysystem ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.743 s
[INFO] Finished at: 2017-11-20T13:35:44-05:00
[INFO] Final Memory: 9M/31M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:2.2-beta-5:assembly (default-cli) on project fuzzysystem: Error reading assemblies: No assembly descriptors found. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by gravityrebel** [comment]
So my guess is that you built this from the top level project, fuzzysystem.

Try running those commands from the lower level project fuzzyserver.

**Pull request merged**
